### ISSUE TITLE
Upload size limit too low

### ISSUE THREAD

**Issue by mikehaertl** [robbertkl/docker-php#1]
I'm using your roundcube image and found, that I can't attach files larger than 1 MB. In the container logfile I see errors like:

> 2017/11/08 07:38:21 [error] 288#0: *3707 client intended to send too large body: 9536080 bytes, client: 192.168.0.1, server: _, request: "POST /?_task=mail&_id=5793423515a02b44f6ecd3&_uploadid=1510126688539&_from=compose&_action=upload HTTP/1.0", host: "mail.example.com", referrer: "https://mail.example.com/?_task=mail&_action=compose&_id=5793423515a02b44f6ecd3"

Can we make the upload size limit configurable?

I assume that this is rather a problem in the Nginx configuration so I'm reporting this here.

**Comment by robbertkl** [comment]
You can create your own `php-fpm.ini.tmpl` and mount it in your container to `/etc/services.d/php/php-fpm.ini.tmpl`.

However, these are the limits currently in that file:
```
upload_max_filesize = 128M
post_max_size = 256M
```

That would suggest much larger POST bodies should be possible...

**Comment by mikehaertl** [comment]
I think it's a Nginx error, not php. It would be great if we could make the `client_max_body_size` configurable. The default is 1m.

Or simply increase it to match the above values (which should both be the same IMHO).

**Comment by robbertkl** [comment]
Yeah, you're right. I'll bump it right away, one moment please.

**Comment by mikehaertl** [comment]
Awesome, thanks for you quick reaction. Could you also trigger a build for your docker images (both, docker-php and docker-roundcube)?

**Comment by robbertkl** [comment]
Just did a push. Builds will be triggered automatically. Should be up soon.

**Comment by robbertkl** [comment]
Builds are done, just did a deploy + test and works like a charm!

Closing the issue, thanks for reporting!

**Comment by mikehaertl** [comment]
Yup, tested it and it works. Thanks again for the fast response!
